# http://www.appveyor.com/docs/build-configuration

# version format
version: 1.0.{build}

# branches to build
branches:
  only:
    - master

# GIT clone directory
clone_folder: c:\projects\curl

platform: x64

configuration: Release

environment:
  DEST: "c:/projects/dest"
  CURL_VERSION: 7.39.0
  CURL_DL_URL: "http://curl.haxx.se/download/"

install:
  - cmd: 'cinst curl'
 
before_build:
  - cmd: 'cd C:\projects\curl'
  - cmd: 'echo Downloading %CURL_DL_URL%curl-%CURL_VERSION%.zip'
  - cmd: 'curl -L -o curl.zip %CURL_DL_URL%curl-%CURL_VERSION%.zip'
  - cmd: '7z x curl.zip > NUL'
  - cmd: 'rename curl-%CURL_VERSION% curl-src'
  - cmd: 'del curl.zip'

# project: C:\projects\curl\curl-src\projects\Windows\VC12\curl.sln
build:
  project: curl-src\projects\Windows\VC12\curl.sln
